roxygen2::roxygenize()
PCMBase::PCMGenerateModelTypes(baseTypes = list(BMkappa = "all"), sourceFile = "R/BMkappaDefaultTypes.R")
PCMBase::PCMGenerateModelTypes(baseTypes = list(OUkappa = "all"), sourceFile = "R/OUkappaDefaultTypes.R")
PCMBase::PCMGenerateModelTypes(baseTypes = list(BM_drift = "all"), sourceFile = "R/BM_driftDefaultTypes.R")
roxygen2::roxygenize()
