roxygen2::roxygenize()
PCMBase::PCMGenerateModelTypes(baseTypes = list(BMkappa = "all"), sourceFile = "R/BMkappaDefaultTypes.R")
PCMBase::PCMGenerateModelTypes(baseTypes = list(OUkappa = "default"), sourceFile = "R/OUkappaDefaultTypes.R")
PCMBase::PCMGenerateModelTypes(baseTypes = list(BM_drift = "default"), sourceFile = "R/BM_driftDefaultTypes.R")
PCMBase::PCMGenerateModelTypes(baseTypes = list(EB = "default"), sourceFile = "R/EBDefaultTypes.R")
PCMBase::PCMGenerateModelTypes(baseTypes = list(EHD = "default"), sourceFile = "R/EHDDefaultTypes.R")
roxygen2::roxygenize()
